# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd76ee45d41e05fbc22a5096a7826134c904e8af730ac159601d29836faa9c1fdc1fa6e657ca3dc7494d7ce8e28a9eab9fa3d9524920f03b866d3474c87f9812

test:
  secret_key_base: 950d989f514db07613aeda929d5cdf1f06d572d4a7d1f1aef9dc174b7e9290f15e702c1e2821ee15601c9fe6ef7842068693dc8d562706437b095503ec24cc90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
